// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngawcovdegciwqxfyafv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nYXdjb3ZkZWdjaXdxeGZ5YWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTQ2OTcsImV4cCI6MjA3MTQzMDY5N30.wjUMqFkjoRG3_d5j2QBO7rfQTW4JPl0nsiGZ4oCl1HE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});